version: '3'

services:
  api:
    build: .
    container_name: customers-api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - cache
  cache:
    container_name: customers-cache
    image: redis:6.2-alpine
    restart: always
    command: redis-server
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - .volumes/cache:/data
